import { useEffect, useState } from "react";
import { getRandomFromArray } from "./utils";

type Kana = [
  kana: string,
  readings: string[],
  type: `${"hiragana" | "katakana"}${"-tenten" | "-maru" | ""}`
];

// function filter(allowed: string[]) {
//   return list.filter((kana) => allowed.includes(kana[0]));
// }

export const useKana = (allowed: string[] = [], newKana = false) => {
  const [filteredList, setFilteredList] = useState<Kana[] /* any */>([]);
  const [kana, setKana] = useState<Kana | undefined>();

  useEffect(() => {
    setFilteredList(kanaList.filter((kana) => allowed.includes(kana[0])));
  }, [allowed]);

  useEffect(() => {
    let nkana: Kana;
    do {
      nkana = getRandomFromArray(filteredList);
    } while (kana && allowed.length > 1 && nkana[0] === kana[0]);
    if (filteredList.length > 0) setKana(nkana);
    else setKana(undefined);
  }, [filteredList, newKana]);

  return kana;
};

export const kanaList: Kana[] = [
  ["あ", ["a"], "hiragana"],
  ["い", ["i"], "hiragana"],
  ["お", ["o"], "hiragana"],
  ["え", ["e"], "hiragana"],
  ["う", ["u"], "hiragana"],
  ["か", ["ka"], "hiragana"],
  ["き", ["ki"], "hiragana"],
  ["こ", ["ko"], "hiragana"],
  ["け", ["ke"], "hiragana"],
  ["く", ["ku"], "hiragana"],
  ["さ", ["sa"], "hiragana"],
  ["し", ["shi", "si"], "hiragana"],
  ["そ", ["so"], "hiragana"],
  ["せ", ["se"], "hiragana"],
  ["す", ["su"], "hiragana"],
  ["た", ["ta"], "hiragana"],
  ["ち", ["chi", "ti"], "hiragana"],
  ["と", ["to"], "hiragana"],
  ["て", ["te"], "hiragana"],
  ["つ", ["tsu", "tu"], "hiragana"],
  ["な", ["na"], "hiragana"],
  ["に", ["ni"], "hiragana"],
  ["の", ["no"], "hiragana"],
  ["ね", ["ne"], "hiragana"],
  ["ぬ", ["nu"], "hiragana"],
  ["は", ["ha"], "hiragana"],
  ["ひ", ["hi"], "hiragana"],
  ["ほ", ["ho"], "hiragana"],
  ["へ", ["he"], "hiragana"],
  ["ふ", ["fu", "hu"], "hiragana"],
  ["ま", ["ma"], "hiragana"],
  ["み", ["mi"], "hiragana"],
  ["も", ["mo"], "hiragana"],
  ["め", ["me"], "hiragana"],
  ["む", ["mu"], "hiragana"],
  ["や", ["ya"], "hiragana"],
  ["ゆ", ["yu"], "hiragana"],
  ["よ", ["yo"], "hiragana"],
  ["ら", ["ra"], "hiragana"],
  ["り", ["ri"], "hiragana"],
  ["ろ", ["ro"], "hiragana"],
  ["れ", ["re"], "hiragana"],
  ["る", ["ru"], "hiragana"],
  ["わ", ["wa"], "hiragana"],
  ["を", ["wo"], "hiragana"],
  ["ん", ["n"], "hiragana"],
  ["が", ["ga"], "hiragana-tenten"],
  ["ぎ", ["gi"], "hiragana-tenten"],
  ["ご", ["go"], "hiragana-tenten"],
  ["げ", ["ge"], "hiragana-tenten"],
  ["ぐ", ["gu"], "hiragana-tenten"],
  ["ぱ", ["pa"], "hiragana-maru"],
  ["ぴ", ["pi"], "hiragana-maru"],
  ["ぽ", ["po"], "hiragana-maru"],
  ["ぺ", ["pe"], "hiragana-maru"],
  ["ぷ", ["pu"], "hiragana-maru"],
  ["ば", ["ba"], "hiragana-maru"],
  ["び", ["bi"], "hiragana-tenten"],
  ["ぼ", ["bo"], "hiragana-tenten"],
  ["べ", ["be"], "hiragana-tenten"],
  ["ぶ", ["bu"], "hiragana-tenten"],
  ["ざ", ["za"], "hiragana-tenten"],
  ["じ", ["di", "ji"], "hiragana-tenten"],
  ["ぞ", ["zo"], "hiragana-tenten"],
  ["ぜ", ["ze"], "hiragana-tenten"],
  ["ず", ["zu"], "hiragana-tenten"],
  ["だ", ["da"], "hiragana-tenten"],
  ["ぢ", ["di", "dzi", "ji"], "hiragana-tenten"],
  ["ど", ["do"], "hiragana-tenten"],
  ["で", ["de"], "hiragana-tenten"],
  ["づ", ["dzu", "du"], "hiragana-tenten"],
  ["ア", ["a"], "katakana"],
  ["イ", ["i"], "katakana"],
  ["オ", ["o"], "katakana"],
  ["エ", ["e"], "katakana"],
  ["ウ", ["u"], "katakana"],
  ["カ", ["ka"], "katakana"],
  ["キ", ["ki"], "katakana"],
  ["コ", ["ko"], "katakana"],
  ["ケ", ["ke"], "katakana"],
  ["ク", ["ku"], "katakana"],
  ["サ", ["sa"], "katakana"],
  ["シ", ["shi", "si"], "katakana"],
  ["ソ", ["so"], "katakana"],
  ["セ", ["se"], "katakana"],
  ["ス", ["su"], "katakana"],
  ["タ", ["ta"], "katakana"],
  ["チ", ["chi", "ti"], "katakana"],
  ["ト", ["to"], "katakana"],
  ["テ", ["te"], "katakana"],
  ["ツ", ["tsu", "tu"], "katakana"],
  ["ナ", ["na"], "katakana"],
  ["ニ", ["ni"], "katakana"],
  ["ノ", ["no"], "katakana"],
  ["ネ", ["ne"], "katakana"],
  ["ヌ", ["nu"], "katakana"],
  ["ハ", ["ha"], "katakana"],
  ["ヒ", ["hi"], "katakana"],
  ["ホ", ["ho"], "katakana"],
  ["ヘ", ["he"], "katakana"],
  ["フ", ["fu", "hu"], "katakana"],
  ["マ", ["ma"], "katakana"],
  ["ミ", ["mi"], "katakana"],
  ["モ", ["mo"], "katakana"],
  ["メ", ["me"], "katakana"],
  ["ム", ["mu"], "katakana"],
  ["ヤ", ["ya"], "katakana"],
  ["ユ", ["yu"], "katakana"],
  ["ヨ", ["yo"], "katakana"],
  ["ラ", ["ra"], "katakana"],
  ["リ", ["ri"], "katakana"],
  ["ロ", ["ro"], "katakana"],
  ["レ", ["re"], "katakana"],
  ["ル", ["ru"], "katakana"],
  ["ワ", ["wa"], "katakana"],
  ["ヲ", ["wo"], "katakana"],
  ["ン", ["n"], "katakana"],
  ["ガ", ["ga"], "katakana-tenten"],
  ["ギ", ["gi"], "katakana-tenten"],
  ["ゴ", ["go"], "katakana-tenten"],
  ["ゲ", ["ge"], "katakana-tenten"],
  ["グ", ["gu"], "katakana-tenten"],
  ["パ", ["pa"], "katakana-maru"],
  ["ピ", ["pi"], "katakana-maru"],
  ["ポ", ["po"], "katakana-maru"],
  ["ペ", ["pe"], "katakana-maru"],
  ["プ", ["pu"], "katakana-maru"],
  ["バ", ["ba"], "katakana-tenten"],
  ["ビ", ["bi"], "katakana-tenten"],
  ["ボ", ["bo"], "katakana-tenten"],
  ["ベ", ["be"], "katakana-tenten"],
  ["ブ", ["bu"], "katakana-tenten"],
  ["ザ", ["za"], "katakana-tenten"],
  ["ジ", ["di", "ji"], "katakana-tenten"],
  ["ゾ", ["zo"], "katakana-tenten"],
  ["ゼ", ["ze"], "katakana-tenten"],
  ["ズ", ["zu"], "katakana-tenten"],
  ["ダ", ["da"], "katakana-tenten"],
  ["ヂ", ["di", "dzi", "ji"], "katakana-tenten"],
  ["ド", ["do"], "katakana-tenten"],
  ["デ", ["de"], "katakana-tenten"],
  ["ヅ", ["dzu", "du"], "katakana-tenten"],
];

export const kanaTypeLookup: { [kana: string]: string } = {
  あ: "hiragana",
  い: "hiragana",
  お: "hiragana",
  え: "hiragana",
  う: "hiragana",
  か: "hiragana",
  き: "hiragana",
  こ: "hiragana",
  け: "hiragana",
  く: "hiragana",
  さ: "hiragana",
  し: "hiragana",
  そ: "hiragana",
  せ: "hiragana",
  す: "hiragana",
  た: "hiragana",
  ち: "hiragana",
  と: "hiragana",
  て: "hiragana",
  つ: "hiragana",
  な: "hiragana",
  に: "hiragana",
  の: "hiragana",
  ね: "hiragana",
  ぬ: "hiragana",
  は: "hiragana",
  ひ: "hiragana",
  ほ: "hiragana",
  へ: "hiragana",
  ふ: "hiragana",
  ま: "hiragana",
  み: "hiragana",
  も: "hiragana",
  め: "hiragana",
  む: "hiragana",
  や: "hiragana",
  ゆ: "hiragana",
  よ: "hiragana",
  ら: "hiragana",
  り: "hiragana",
  ろ: "hiragana",
  れ: "hiragana",
  る: "hiragana",
  わ: "hiragana",
  を: "hiragana",
  ん: "hiragana",
  が: "hiragana-tenten",
  ぎ: "hiragana-tenten",
  ご: "hiragana-tenten",
  げ: "hiragana-tenten",
  ぐ: "hiragana-tenten",
  ぱ: "hiragana-maru",
  ぴ: "hiragana-maru",
  ぽ: "hiragana-maru",
  ぺ: "hiragana-maru",
  ぷ: "hiragana-maru",
  ば: "hiragana-maru",
  び: "hiragana-tenten",
  ぼ: "hiragana-tenten",
  べ: "hiragana-tenten",
  ぶ: "hiragana-tenten",
  ざ: "hiragana-tenten",
  じ: "hiragana-tenten",
  ぞ: "hiragana-tenten",
  ぜ: "hiragana-tenten",
  ず: "hiragana-tenten",
  だ: "hiragana-tenten",
  ぢ: "hiragana-tenten",
  ど: "hiragana-tenten",
  で: "hiragana-tenten",
  づ: "hiragana-tenten",
  ア: "katakana",
  イ: "katakana",
  オ: "katakana",
  エ: "katakana",
  ウ: "katakana",
  カ: "katakana",
  キ: "katakana",
  コ: "katakana",
  ケ: "katakana",
  ク: "katakana",
  サ: "katakana",
  シ: "katakana",
  ソ: "katakana",
  セ: "katakana",
  ス: "katakana",
  タ: "katakana",
  チ: "katakana",
  ト: "katakana",
  テ: "katakana",
  ツ: "katakana",
  ナ: "katakana",
  ニ: "katakana",
  ノ: "katakana",
  ネ: "katakana",
  ヌ: "katakana",
  ハ: "katakana",
  ヒ: "katakana",
  ホ: "katakana",
  ヘ: "katakana",
  フ: "katakana",
  マ: "katakana",
  ミ: "katakana",
  モ: "katakana",
  メ: "katakana",
  ム: "katakana",
  ヤ: "katakana",
  ユ: "katakana",
  ヨ: "katakana",
  ラ: "katakana",
  リ: "katakana",
  ロ: "katakana",
  レ: "katakana",
  ル: "katakana",
  ワ: "katakana",
  ヲ: "katakana",
  ン: "katakana",
  ガ: "katakana-tenten",
  ギ: "katakana-tenten",
  ゴ: "katakana-tenten",
  ゲ: "katakana-tenten",
  グ: "katakana-tenten",
  パ: "katakana-maru",
  ピ: "katakana-maru",
  ポ: "katakana-maru",
  ペ: "katakana-maru",
  プ: "katakana-maru",
  バ: "katakana-tenten",
  ビ: "katakana-tenten",
  ボ: "katakana-tenten",
  ベ: "katakana-tenten",
  ブ: "katakana-tenten",
  ザ: "katakana-tenten",
  ジ: "katakana-tenten",
  ゾ: "katakana-tenten",
  ゼ: "katakana-tenten",
  ズ: "katakana-tenten",
  ダ: "katakana-tenten",
  ヂ: "katakana-tenten",
  ド: "katakana-tenten",
  デ: "katakana-tenten",
  ヅ: "katakana-tenten",
};
